# Generated by Django 5.0.3 on 2024-04-06 10:21

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        ("stages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="stage",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="stages.stage",
            ),
            preserve_default=False,
        ),
    ]
