# Generated by Django 5.0.3 on 2024-04-14 11:46

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_image_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.FilePathField(path="media/"),
        ),
    ]
