version: '3.8'

volumes:
  pgdbdata:
    driver: local

services:
  django:
    build: 
      context: .
    env_file:
      - .env
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
      - 4000:4000
    depends_on:
      - db
      - redis

  # client:
  #     build:
  #       context: src
  #       dockerfile: Dockerfile
  #     ports:
  #         - 80:80
  #     volumes:
  #         - ./src:/usr/share/nginx/html

  celery:
        build: .
        container_name: celery
        command: celery -A apps worker -l INFO
        volumes:
            - .:/code
        depends_on:
            - django
            - redis

  redis:
        image: "redis:alpine"
        container_name: redis
        ports:
            - "6379:6379"
        command: redis-server --appendonly yes

  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
