# Generated by Django 5.0.3 on 2024-03-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_mileage_alter_car_registration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
