# Generated by Django 5.0.3 on 2024-04-14 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_remove_car_registration_date"),
        ("stages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="stage",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stage",
                to="stages.stage",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="car",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
