# Generated by Django 5.0.3 on 2024-04-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FilePathField()),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
