# Generated by Django 5.0.3 on 2024-04-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="type",
            field=models.CharField(
                choices=[("INV", "Invoice"), ("CON", "Contract")],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
