# Generated by Django 5.0.3 on 2024-04-14 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0005_alter_car_stage_alter_car_user"),
        ("documents", "0002_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="car",
            field=models.ForeignKey(
                default=2, on_delete=django.db.models.deletion.CASCADE, to="cars.car"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FilePathField(path="media/"),
        ),
    ]
