# Generated by Django 5.0.3 on 2024-04-14 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_document_car_alter_document_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="owner",
        ),
    ]
