# Generated by Django 5.0.3 on 2024-04-13 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_notificationsettings_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationsettings",
            name="user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
