# Generated by Django 5.0.3 on 2024-04-11 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schedule",
            options={"verbose_name": "schedule", "verbose_name_plural": "schedules"},
        ),
        migrations.AlterModelTable(
            name="schedule",
            table="schedule",
        ),
    ]
