# Generated by Django 5.0.3 on 2024-04-14 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_alter_schedule_options_alter_schedule_table"),
        ("stages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="stage",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stages.stage",
            ),
        ),
    ]
